# docker-compose.yml

services:
  db:
    image: postgres:latest # Or a specific version like postgres:15
    container_name: draft_guru_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # Expose PostgreSQL port locally if needed for direct access
    volumes:
      - draft_guru_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: draft_guru_app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # Wait for db to be ready
    ports:
      - "4001:4000" # Map container port 4001 to host port 4000
    environment:
      MIX_ENV: prod # Run in production mode inside container
      PHX_SERVER: "true" # Start the Phoenix server
      PORT: 4000
      PHX_HOST: localhost 
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
      POOL_SIZE: 10 # Or adjust as needed
    command: ["/app/bin/draft_guru", "start"] # Use start here, migrations run separately with compose
    # If not using the Release module in CMD, you can run migrations manually after starting:
    # docker-compose exec app /app/bin/draft_guru eval 'DraftGuru.Release.migrate()'

volumes:
  draft_guru_postgres_data: # Persist database data