version: "3.9"

services:
  app:
    build: .
    # or `image: jonathanbechtel/draft_guru:staging` once you push
    env_file:
      - .env
    environment:
      # Phoenix / release flags
      PHX_SERVER: "true"
      PORT: ${PORT:-4000}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

      # Postgres (Neon) -- include `sslmode=require`
      DATABASE_URL: ${DATABASE_URL}

      # Optional: pool & host config you already use
      POOL_SIZE: ${POOL_SIZE:-10}
      PHX_HOST:  ${PHX_HOST:-localhost}
      PUBLIC_CANONICAL_HOST: ${PUBLIC_CANONICAL_HOST:-localhost}
    ports:
      - "${APP_PORTS:-4000:4000}"
    restart: unless-stopped