services:      
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile   
      args:
        MIX_ENV: dev
    volumes:
      - .:/app                
    command: ["mix", "phx.server"]
    ports:
      - "4001:4000"